package application;

import application.gantt.GanttController;
import application.memory_map.MemoryMapController;
import application.statistics.StatisticsController;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.ChoiceBox;
import javafx.scene.control.MenuItem;
import javafx.scene.control.Tab;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

public class MainController {
	
	// MENU
	@FXML private MenuItem menuItemAbrir;
	@FXML private MenuItem menuItemGuardar;
	
	// PESTANIAS
	@FXML private Tab particionesFijas;
	@FXML private Tab colasMultinivel;
	
	// CAMPOS
	@FXML private TextField limiteMemoria;
	@FXML private TextField quantum;

	// BOTONES
	@FXML private Button executeButton;
	@FXML private Button memoryMapButton;
	@FXML private Button ganttButton;
	@FXML private Button statisticsButton;
	
	// CHOICEBOX
	private ObservableList<String> listaParticiones = FXCollections.observableArrayList("Fijas", "Variables");
	@FXML private ChoiceBox<String> particiones;
	
	private ObservableList<String> listaPoliticasFijas = FXCollections.observableArrayList("First-Fit", "Best-Fit");
	private ObservableList<String> listaPoliticasVariables = FXCollections.observableArrayList("First-Fit", "Worst-fit", "Base y Desplaz.");
	@FXML private ChoiceBox<String> politicas;
	
	private ObservableList<String> listaAlgoritmos = FXCollections.observableArrayList("FCFS", "Prioridades", "Round-Robin", "Colas Multinivel");
	@FXML private ChoiceBox<String> algoritmos;
	
	private ObservableList<String> listaAlgoritmosCM = FXCollections.observableArrayList("FCFS", "Prioridades", "Round-Robin");
	@FXML private ChoiceBox<String> colaMultinivelA1;
	@FXML private ChoiceBox<String> colaMultinivelA2;
	@FXML private ChoiceBox<String> colaMultinivelA3;
	@FXML private ChoiceBox<String> colaMultinivelA4;

	@FXML
	public void initialize() {

		// CARGAMOS LOS CHOICEBOX
		particiones.setValue("Fijas");
		particiones.setItems(listaParticiones);
		
		algoritmos.setValue("FCFS");
		algoritmos.setItems(listaAlgoritmos);
		
		colaMultinivelA1.setValue("FCFS");
		colaMultinivelA1.setItems(listaAlgoritmosCM);
		colaMultinivelA2.setValue("FCFS");
		colaMultinivelA2.setItems(listaAlgoritmosCM);
		colaMultinivelA3.setValue("FCFS");
		colaMultinivelA3.setItems(listaAlgoritmosCM);
		colaMultinivelA4.setValue("FCFS");
		colaMultinivelA4.setItems(listaAlgoritmosCM);
		
	}
	
	/*
	 * ------------------------------ EVENTOS MENU ------------------------------
	 * 
	 */

	// EVENTO MENU ABRIR -> VENTANA ABRIR ARCHIVO
	@FXML
	public void menuItemAbrir(ActionEvent event) {
		loadWindow("/application/save_load/Load.fxml", "Abrir archivo");
	}
	
	// EVENTO MENU GUARDAR -> VENTANA GUARDAR ARCHIVO
	@FXML
	public void menuItemGuardar(ActionEvent event) {
		loadWindow("/application/save_load/Save.fxml", "Guardar archivo");
	}
	
	/*
	 * ------------------------------ EVENTOS BOTONES ------------------------------
	 * 
	 */
	
	// METODO PARA CARGAR LAS VISTAS
	public void loadWindow(String location, String title) {
		try {
			Parent parent = FXMLLoader.load(getClass().getResource(location));
			Scene scene = new Scene(parent);

			Stage stage = new Stage();
			stage.setTitle(title);
			stage.setScene(scene);
			stage.show();

		} catch (Exception e) {
			System.out.println("Error cargando vista: '" + title + "'. ERROR: " + e.getMessage());
		}
	}
	

	// EVENTO BOTON EJECUTAR
	@FXML
	public void execute(ActionEvent event) {
		// TODO Autogenerated
	}

	// EVENTO BOTON MAPA DE MEMORIA
	@FXML
	public void loadMemoryMap(ActionEvent event) {
//		loadWindow("/application/memory_map/MemoryMap.fxml", "Mapa de memoria");
		MemoryMapController.MemoryMap();
	}

	// EVENTO BOTON GANTT
	@FXML
	public void loadGantt(ActionEvent event) {
//		loadWindow("/application/gantt/Gantt.fxml", "Diagrama de Gantt");
		GanttController.GanttDiagram();
	}

	// EVENTO BOTON ESTADISTICAS
	@FXML
	public void loadStatistics(ActionEvent event) {
//		loadWindow("/application/statistics/Statistics.fxml", "Estadísticas");
		StatisticsController.Statistics();
	}
	
	/*
	 * ------------------------------ EVENTOS CHOICEBOX ------------------------------
	 * 
	 */
	
	// EVENTO CHOICEBOX PARTICION FIJA/VARIABLE
	@FXML
	public void particionFijaVariable(ActionEvent event) {
		if (particiones.getValue().equals("Fijas")) {
			particionesFijas.setDisable(false);
			politicas.setItems(listaPoliticasFijas);
		}
		else {
			particionesFijas.setDisable(true);
			politicas.setItems(listaPoliticasVariables);
		}
		politicas.setValue("First-Fit");
	}
	
	// EVENTO CHOICEBOX ALGORITMO PESTANIA CONDICIONES INICIALES
	@FXML
	public void algoritmoCondicionesIniciales(ActionEvent event) {
		switch (algoritmos.getValue()) {
		case "Round-Robin":
			quantum.setDisable(false);
			colasMultinivel.setDisable(true);
			break;
		case "Colas Multinivel":
			quantum.setDisable(true);
			colasMultinivel.setDisable(false);
			break;
		default:
			quantum.setDisable(true);
			colasMultinivel.setDisable(true);
			break;
		}
	}

	/*
	 * ------------------------------ RESTRICCIONES ------------------------------
	 * 
	 */
	
	// RESTRICCION CAMPO LIMITE DE MEMORIA
	@FXML
	public void limiteMemoria(ActionEvent event) {
		try {
			int limite = Integer.parseInt(limiteMemoria.getText().trim());
			if (limite < 100 || limite > 1000) {
				Alert alert = new Alert(AlertType.ERROR);
				alert.setTitle("Error - Simulador");
				alert.setHeaderText(null);
				alert.setContentText("Ingresar un entero entre 100 y 1000.");
				alert.showAndWait();
			}
		} catch (Exception e) {
			System.out.println("Error en ingreso de datos en campo 'Límite Memoria'. ERROR: " + e.getMessage());
			Alert alert = new Alert(AlertType.ERROR);
			alert.setTitle("Error - Simulador");
			alert.setHeaderText(null);
			alert.setContentText("Ingresar un entero.");
			alert.showAndWait();
		}
	}
	
}
